name: CI/CD

on:
  push:
    tags:
    - 'v*.*.*'

env:
  MY_VAR_01: 'HELLO'
  MY_VAR_02: 'WORLD'
  MY_FOLDER_01: 'my_folder'
  JAVA_VERSION: '15'
  JAVA_DISTRIBUTION: 'adopt'
  
jobs:
  my_tests_01:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
            java-version: ${{ env.JAVA_VERSION }}
            distribution: ${{ env.JAVA_DISTRIBUTION }}
        
      - name: Do sth. multi
        run: |
          echo $MY_VAR_01
          echo "$MY_VAR_01"
          echo "${MY_VAR_01}"
          echo ${{env.MY_VAR_01}}
          echo "${{env.MY_VAR_01}}"
          cat $MY_FOLDER_01/myfile.txt
          cat "$MY_FOLDER_01"/myfile.txt
          cat "${MY_FOLDER_01}"/myfile.txt
          cat ${{env.MY_FOLDER_01}}/myfile.txt
          cat "${{env.MY_FOLDER_01}}"/myfile.txt
          sh ${{env.MY_FOLDER_01}}/myscript.sh ${{env.MY_VAR_01}} ${{env.MY_VAR_02}}
          sh ${{env.MY_FOLDER_01}}/myscript.sh "${{env.MY_VAR_01}}" "${{env.MY_VAR_02}}"

  my_tests_02:
    runs-on: macos-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
            java-version: ${{ env.JAVA_VERSION }}
            distribution: ${{ env.JAVA_DISTRIBUTION }}
        
      - name: Do sth. multi
        run: |
          echo $MY_VAR_01
          echo "$MY_VAR_01"
          echo "${MY_VAR_01}"
          echo ${{env.MY_VAR_01}}
          echo "${{env.MY_VAR_01}}"
          cat $MY_FOLDER_01/myfile.txt
          cat "$MY_FOLDER_01"/myfile.txt
          cat "${MY_FOLDER_01}"/myfile.txt
          cat ${{env.MY_FOLDER_01}}/myfile.txt
          cat "${{env.MY_FOLDER_01}}"/myfile.txt
          sh ${{env.MY_FOLDER_01}}/myscript.sh ${{env.MY_VAR_01}} ${{env.MY_VAR_02}}
          sh ${{env.MY_FOLDER_01}}/myscript.sh "${{env.MY_VAR_01}}" "${{env.MY_VAR_02}}"